services:
  - type: web
    name: youthmvd-api
    env: docker
    repo: https://github.com/crashmirage/YOUTHMVD
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"   # ✅ Doit matcher le CMD (tu avais 8000 ici, mismatch !)
